import {
  Bitcoin,
  Wallet,
  Landmark,
  Gem,
  Layers,
  Cpu,
  Zap,
  Rocket,
  Globe,
  Code,
  Shield,
  Lightbulb,
  Users,
  MessageSquare,
  Banknote,
  BarChart,
  Briefcase,
  Smartphone,
  Gamepad2,
} from "lucide-react"

export const boards = [
  // TRON Ecosystem Boards
  {
    id: "tron-general",
    name: "TRON General",
    chinese: "波场综合",
    description: "General discussion about TRON blockchain and ecosystem",
    icon: Bitcoin,
    postCount: 324,
    tags: ["tron", "blockchain", "crypto"],
  },
  {
    id: "tron-defi",
    name: "TRON DeFi",
    chinese: "波场金融",
    description: "Discussions about DeFi projects and protocols on TRON",
    icon: Wallet,
    postCount: 156,
    tags: ["tron", "defi", "finance", "crypto"],
  },
  {
    id: "tron-governance",
    name: "TRON Governance",
    chinese: "波场治理",
    description: "Discussions about TRON governance and proposals",
    icon: Landmark,
    postCount: 89,
    tags: ["tron", "governance", "dao", "crypto"],
  },
  {
    id: "tron-nfts",
    name: "TRON NFTs",
    chinese: "波场NFT",
    description: "Discussions about NFTs on the TRON blockchain",
    icon: Gem,
    postCount: 112,
    tags: ["tron", "nft", "art", "crypto"],
  },
  {
    id: "tron-dapps",
    name: "TRON dApps",
    chinese: "波场应用",
    description: "Discussions about decentralized applications on TRON",
    icon: Layers,
    postCount: 201,
    tags: ["tron", "dapps", "development", "crypto"],
  },
  {
    id: "tron-tech",
    name: "TRON Tech",
    chinese: "波场技术",
    description: "Technical discussions about TRON blockchain technology",
    icon: Cpu,
    postCount: 178,
    tags: ["tron", "technology", "development", "crypto"],
  },
  {
    id: "tron-energy",
    name: "TRON Energy",
    chinese: "波场能量",
    description: "Discussions about TRON energy and resource model",
    icon: Zap,
    postCount: 67,
    tags: ["tron", "energy", "resources", "crypto"],
  },
  {
    id: "tron-future",
    name: "TRON Future",
    chinese: "波场未来",
    description: "Discussions about the future of TRON and upcoming developments",
    icon: Rocket,
    postCount: 94,
    tags: ["tron", "future", "roadmap", "crypto"],
  },

  // General Crypto Boards
  {
    id: "crypto-markets",
    name: "Crypto Markets",
    chinese: "加密市场",
    description: "Discussions about cryptocurrency markets, trends, and analysis",
    icon: BarChart,
    postCount: 287,
    tags: ["crypto", "markets", "trading", "analysis"],
  },
  {
    id: "defi-general",
    name: "DeFi General",
    chinese: "DeFi综合",
    description: "General discussions about decentralized finance across all blockchains",
    icon: Banknote,
    postCount: 203,
    tags: ["defi", "finance", "crypto", "yield"],
  },
  {
    id: "nft-marketplace",
    name: "NFT Marketplace",
    chinese: "NFT市场",
    description: "Discussions about NFT marketplaces, collections, and trends",
    icon: Briefcase,
    postCount: 176,
    tags: ["nft", "art", "marketplace", "crypto"],
  },

  // Web3 Boards
  {
    id: "web3-development",
    name: "Web3 Development",
    chinese: "Web3开发",
    description: "Discussions about Web3 development, tools, and frameworks",
    icon: Code,
    postCount: 142,
    tags: ["web3", "development", "coding", "blockchain"],
  },
  {
    id: "dao-governance",
    name: "DAO Governance",
    chinese: "DAO治理",
    description: "Discussions about DAOs and decentralized governance models",
    icon: Users,
    postCount: 98,
    tags: ["dao", "governance", "voting", "community"],
  },
  {
    id: "metaverse",
    name: "Metaverse",
    chinese: "元宇宙",
    description: "Discussions about metaverse projects, virtual worlds, and digital identity",
    icon: Globe,
    postCount: 156,
    tags: ["metaverse", "virtual", "digital", "identity"],
  },

  // Technology Boards
  {
    id: "blockchain-tech",
    name: "Blockchain Tech",
    chinese: "区块链技术",
    description: "Technical discussions about blockchain technology and protocols",
    icon: Shield,
    postCount: 167,
    tags: ["blockchain", "technology", "protocols", "consensus"],
  },
  {
    id: "crypto-gaming",
    name: "Crypto Gaming",
    chinese: "加密游戏",
    description: "Discussions about blockchain games, play-to-earn, and GameFi",
    icon: Gamepad2,
    postCount: 134,
    tags: ["gaming", "gamefi", "p2e", "crypto"],
  },
  {
    id: "mobile-crypto",
    name: "Mobile Crypto",
    chinese: "移动加密",
    description: "Discussions about mobile cryptocurrency wallets and applications",
    icon: Smartphone,
    postCount: 89,
    tags: ["mobile", "wallet", "apps", "crypto"],
  },

  // Innovation Boards
  {
    id: "crypto-innovation",
    name: "Crypto Innovation",
    chinese: "加密创新",
    description: "Discussions about innovative projects and ideas in the crypto space",
    icon: Lightbulb,
    postCount: 112,
    tags: ["innovation", "ideas", "projects", "crypto"],
  },
  {
    id: "community-chat",
    name: "Community Chat",
    chinese: "社区聊天",
    description: "General discussions and community building for crypto enthusiasts",
    icon: MessageSquare,
    postCount: 345,
    tags: ["community", "chat", "discussion", "crypto"],
  },
]
